config/routes.rb
Rails.application.routes.draw do
  get 'projects/dashboard'
  get 'projects/create'

  root 'projects#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, :description, :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23"

  def dashboard
    @project = Project.new
    if params[:state].present?
      @projects = Project.where('state = ?', params[:state])
    else
      @projects = Project.all
    end
  end

  def create
    @project = Project.create(name: params[:name],
                              description: params[:description],
                              started: params[:started],
                              finished: params[:finished],
                              state: params[:state])
      @projects = Project.all
      render :dashboard 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorProyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

    <%= yield %>
  
   
  </body>
</html>

app/views/projects/dashboard.html.erb
<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> Este proyecto no ha sido guardado:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

<h1>Nuevo Proyecto</h1>
<form action="<%= projects_create_path %>">
    Nombre del proyecto: <input name="name" type="text"><br>
    Descripcion: <textarea name="description" id="" cols="30" rows="10"></textarea><br>
    Fecha de comienzo: <input name="started" type="date" value="<%= '08/01/2021' %>"><br>
    Fecha de termino: <input name="finished" type="date"><br>
    Estado: <select name="state"><br>
        <option value="propuesta">Propuesta</option>
        <option value="en progreso">En progreso</option>
        <option value="terminado">Terminado</option>
    </select><br>

    <input type="submit" value="Guardar">

</form>

<h2>Gestor de Proyectos</h2>
<form action="<%= projects_dashboard_path %>">
    <select name="state"><br>
        <option value="">Todos</option>
        <option value="propuesta">Propuesta</option>
        <option value="en progreso">En progreso</option>
        <option value="terminado">Terminado</option>
    </select><br>
    <input type="submit" value="Buscar">
</form>

<table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Fecha de comienzo</th>
        <th>Fecha de termino</th>
        <th>Estado</th>
      </tr>
    </thead>
  
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.description %></td>
          <td><%= project.started %></td>
          <td><%= project.finished %></td>
          <td><%= project.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  